UPRI-NOAH/noah-frontend

src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.ts
src/app/features/know-your-hazards/services/kyh.service.ts
src/app/shared/data/kyh_combined_tileset.json

- Show the hazard maps for the whole philippines
- The critical facilities aren't included yet

refactor(know-your-hazards): show hazard maps for the whole philippines

---

src/app/features/home/components/footer/footer.component.html
src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.scss
src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.ts
src/app/features/noah-playground/components/map-playground/map-playground.component.html
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.scss
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts

- Mapbox logo for landing page footer
- responsive logo for kyh and playground page for mobile view and desktop view
- rearrange map style button (terrain, satellite) for playground page
- KYH Page
-mobile view
- desktop view
- Playground Page
- Mobile view
- Desktop view
- Footer
- Desktop view
- mobile view
https://www.loom.com/share/00154a9b62964e67b94e3be06bd6bf7b
- mapboxgl-ctrl-bottom-right
* Im using this class pero di nag work yung toggle, ginawan ko lang ng ibang way para ma toggle sya.
-mapboxgl-ctrl-bottom-left
* Nagamit ko po itong class na to.

feat: mapbox logo for footer and kyh, playground responsive

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/store/noah-playground.store.ts
src/app/shared/mocks/critical-facilities.ts

The critical facilities still cause the map to lag despite our efforts to optimize our methods of loading the hazard maps source files. This MR aims to address this issue by using the size-optimized files for the critical facilities.

feat(playground): get critical facilities from the optimized file at s3

---

src/app/features/home/pages/landing-page/landing-page.component.html

- responsive landing page kyh white platform
-  https://github.com/UPRI-NOAH/noah-frontend/pull/new/landingpage-kyh/white

style(landing-page): responsive search bubble

---

src/app/features/home/home-routing.module.ts
src/app/features/home/home.module.ts
src/app/features/home/pages/bibliography/bibliography.component.html
src/app/features/home/pages/bibliography/bibliography.component.spec.ts
src/app/features/home/pages/bibliography/bibliography.component.ts
src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html

- Rebased continuation of  https://github.com/UPRI-NOAH/noah-frontend/pull/165/commits

feat: added bibliography

---

src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html

- remove scroll for mobile view in playground and KYH page
https://www.loom.com/share/10cb371679fc484290acd3b17ff58da7

style: remove overflow scroll in bottom panels for mobile view

---

src/app/features/home/pages/bibliography/bibliography.component.html

- removed underline in bibliography

style(bibliography): remove underline in bibliography

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/components/weather/weather.component.html

1. Zoom out to show PAR view
2. Added HIMAWARI label

fix(playground): weather image zoom layer to PAR view; label update

---

src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html

- Disclaimer in kyh page
-Desktop view
- Mobile view

feat(know-your-hazards): disclaimer 

---

src/app/features/noah-playground/components/sensors-group/sensors-group.component.html

- added DOST EULA inside noah playground under sensors dropdown

feat: added DOST copyright

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

This will trigger a build and deployment to both the ASTI server  (.72) and AWS Infra (S3 + CF).

Added github actions workflow for auto deployment to both s3 and asti servers

---

src/app/features/home/pages/bibliography/bibliography.component.html

Will revert this small change upon validation.

Checking proper automation workflow. 

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
src/app/features/home/pages/bibliography/bibliography.component.html

This PR just tests the build and deployment workflow to AWS infra (S3+Cloudfront)

S3 Deployment Validation

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts

- Change url for Himawari while PR for weather satellite in still on going

fix(playground): change url for himawari

---

src/app/shared/mocks/flood.ts

fix(playground): change unstable slopes low to high in gridcode

---

src/app/features/know-your-hazards/pages/base/base.component.html

fix(know-your-hazards): change text info in side bar base component

---

.github/workflows/deploy_production.yml

Modified AWS S3 bucket name and Cloudfront Distribution ID

ci: modified cd workflows for production deployment

---

src/app/features/noah-playground/services/sensor.service.ts

- Change Base URL from https://noah-api.site to https://noah-api.up.edu.ph

fix(studio): change sensor base url

---

src/app/features/know-your-hazards/services/kyh.service.ts

- Remove alluvial fan and debris flow layer in know-your-hazards

fix(kyh): remove alluvial fan and debris flow in kyh

---

src/app/features/know-your-hazards/services/hazards.service.ts
src/app/features/noah-playground/components/map-playground/map-playground.component.ts

----
- line 79 set radius  '0'

fix(kyh): remove set value of radius for kyh assessments

---

src/app/features/noah-playground/services/qc-sensor-chart.service.ts
src/app/features/noah-playground/services/qc-sensor.service.ts
src/app/shared/components/summary/summary.component.html
src/app/shared/components/summary/summary.component.ts

- added label for summary dashboard column latest data
- change rain value to `acc`
- added latest data endpoint from backend

feat(qc-iot): summary dashboard label and rain value

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/services/qc-sensor-chart.service.ts
src/app/features/noah-playground/services/qc-sensor.service.ts

- Display all data from paginated API
- after the data is loaded wait for 3.5 secs to default zoom to 1 Day
https://www.loom.com/share/a33f95774ac64336ae61434d84c2246f

 feat(qc-iot): display All data

---

src/app/features/noah-playground/components/qc-sensor-solo/qc-sensor-solo.component.ts
src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.html
src/app/shared/components/summary/summary.component.html
src/app/shared/components/summary/summary.component.scss

fix(qc-studio): fix ui for summary dashboard and name sensor type

---

src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html

- added a minimize icon for kyh legend

feat(kyh): update kyh legend in map

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/store/noah-playground.store.ts

fix(qc-iot): fix bugs from QA

---

src/app/features/noah-playground/components/contour-maps/contour-maps.component.ts
src/app/features/noah-playground/store/noah-playground.store.ts

fix(playground): remove 24hour lapse contour

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts

- keep open the popup chart when hovering other sensor
https://www.loom.com/share/9d47d9de6f98471fb8d3edd7ff4381eb

feat(qc-iot): QA fixed for hovering sensor

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts

- hide popup when unchecked IoT sidebar

fix(qc-iot-qa): when IoT sidebar unchecked hide popup

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts

- added hover battery percentage
- the data from API (not ngrok)

feat(qc-iot): battery percentage

---

src/app/shared/components/summary/summary.component.html

- rain level to dash
- mobile view 
- displaying flood level

feat(qc-iot): QC IoT summary dashboard

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/shared/components/summary/summary.component.ts

- computation for summary dashboard
- condition if muni logged in and download data
- condition if someone logged in and download data
https://www.loom.com/share/29f85f3eeb6143b9a4ae2473070089b7

fix(iot): fix bugs for qc and laguna iot combination

---

src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
src/app/features/noah-playground/services/modal-services.service.ts
src/app/features/noah-playground/services/qc-sensor-chart.service.ts
src/app/features/noah-playground/services/qc-sensor.service.ts
src/app/shared/components/alert/alert.component.html
src/app/shared/components/alert/alert.component.ts
src/app/shared/components/qc-login/qc-login.component.html
src/app/shared/components/qc-login/qc-login.component.ts
src/app/shared/components/summary/summary.component.ts

- loading while the graph didn't show up
- login modal for different municipality
- warning alert for muni try to download other muni
- delete unused codes
- refactor some of codes
https://www.loom.com/share/d25bb7ab77ff465c92cfe6f7df18ee3c

fix(iot): fix bug and errors in login modal ang graph display

---

CHANGELOG.md
src/app/features/noah-playground/components/map-playground/map-playground.component.ts

fix(qc-iot): add latest data in popup map display

---

src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.html
src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.ts
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
src/app/features/noah-playground/services/modal.service.ts

- toggle modal for 4as summary

feat(4as-modal): popup modal when calculate risk button is clicked

---

src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
src/app/features/noah-playground/services/risk-assessment.service.ts

feat(4as): add data in modal risk assessment

---

src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html

- remove the word available
- remove border

feat(4as): changes on summary 

---

src/app/features/noah-playground/components/earthquake-solo/earthquake-solo.component.html
src/app/features/noah-playground/components/earthquake-solo/earthquake-solo.component.ts
src/app/features/noah-playground/components/map-playground/map-playground.component.html
src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/services/earthquake-data.service.ts
src/app/features/noah-playground/services/noah-playground.service.ts
src/app/features/noah-playground/store/noah-playground.store.ts

- displaying main point from backend coordinates
- click main point to burst the new point depending on floor number

feat(earthquake): displaying earthquake burst new points

---

src/app/features/noah-playground/components/boundaries-group/boundaries-group.component.html
src/app/features/noah-playground/components/boundaries-group/boundaries-group.component.spec.ts
src/app/features/noah-playground/components/boundaries-group/boundaries-group.component.ts
src/app/features/noah-playground/components/boundaries-solo/boundaries-solo.component.html
src/app/features/noah-playground/components/boundaries-solo/boundaries-solo.component.spec.ts
src/app/features/noah-playground/components/boundaries-solo/boundaries-solo.component.ts
src/app/features/noah-playground/components/map-playground/map-playground.component.html
src/app/features/noah-playground/components/map-playground/map-playground.component.ts
src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.ts
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.scss
src/app/features/noah-playground/noah-playground.module.ts
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
src/app/features/noah-playground/services/modal.service.ts
src/app/features/noah-playground/services/noah-playground.service.ts
src/app/features/noah-playground/services/qc-login.service.ts
src/app/features/noah-playground/services/risk-assessment.service.ts
src/app/features/noah-playground/store/noah-playground.store.ts
src/app/shared/components/login/login.component.html
src/app/shared/components/login/login.component.ts
src/app/shared/components/qc-login/qc-login.component.html
src/app/shared/components/qc-login/qc-login.component.ts

- [PR 365](https://github.com/UPRI-NOAH/noah-frontend/pull/365) - IoT Login and Logout
- [PR 366](https://github.com/UPRI-NOAH/noah-frontend/pull/366) - boundary new feature
- [PR 369](https://github.com/UPRI-NOAH/noah-frontend/pull/369) - toggle boundaries and devs account
- [PR 370](https://github.com/UPRI-NOAH/noah-frontend/pull/370) - add municipal and provincial boundaries
- [PR 372](https://github.com/UPRI-NOAH/noah-frontend/pull/372) - popup and legend display

feat(noah): create staging for new feature

---

src/app/features/noah-playground/components/earthquake-group/earthquake-group.component.html
src/app/features/noah-playground/components/earthquake-solo/earthquake-solo.component.html
src/app/shared/components/summary-earthquake/summary-earthquake.component.html

fix(eq): display of data value in dashboard

---

.gitignore
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
src/app/features/noah-playground/services/risk-assessment.service.ts

- Different popup modal for exposure assessment summary dashboard is used for mobile view. NOAH Studio nav list for mobile view has been optimized.

feat(studio)(exposure-assessment)[PWA]: Design mobile view for exposure assessment summary dashboard and optimize NOAH Studio nav list for mobile view

---

src/app/features/know-your-hazards/components/hazard-button/hazard-button.component.html
src/app/features/know-your-hazards/pages/base/base.component.html
src/app/features/know-your-hazards/pages/base/base.component.ts
src/app/features/know-your-hazards/pages/flood/flood.component.html
src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
src/app/features/know-your-hazards/pages/landslides/landslides.component.html
src/app/features/know-your-hazards/pages/storm-surge/storm-surge.component.html
src/environments/environment.ts

- Added pagination for mobile view
- Made menu in mobile view floating
- Fixed header in mobile view

[WIP]feat(KYH)[PWA]: KYH mobile view
